### ISSUE TITLE
Array parent class

### ISSUE THREAD

**Issue by kaylindevchand** [chasebish/cs4500_assignment1_part2#2]
Can there be a parent class that the four arrays inherit from? This way we can abstract the common functionality like hash, length, clear, equals, and "private" helper methods.

Also in the BoolArray class, the equals method should be:
bool equals(Object* obj);

**Comment by chasebish** [comment]
just pushed

some notes:
- created Array class. should not actually be used, but instead inherited (similar to Object)
- changed all pointers to const
- fixed small typo in BoolArray

If you have any requests in the future, feel free to make a PR
