### ISSUE TITLE
size_t can't be negative

### ISSUE THREAD

**Issue by kaylindevchand** [chasebish/cs4500_assignment1_part2#3]
For the index_of methods, the comments say to return -1 but the return type size_t is unsigned. Maybe it could return SIZE_MAX?

**Comment by chasebish** [comment]
I believe that assigning a size_t to -1 will automatically give it the value of a max integer

**Comment by chasebish** [comment]
both ways should work

**Comment by kaylindevchand** [comment]
you're right.
