### ISSUE TITLE
What behavior when get() cannot find object? replace() can't find object?

### ISSUE THREAD

**Issue by csstransky** [chasebish/cs4500_assignment1_part2#8]
What specific behavior do you want when a get(index) has nothing or is out of bounds?

Currently, we've been returning the last element in the Array when the index is out of bounds, but then we run into issues when the Array has no elements.
+ What do we return for a Float/Int with no elements? 0? -1? Throw an error? NULL?
+ What do we return for a Boolean? 
+ String/Object?
+ What happens when we're out of bounds?

--------------------------

Also, what do you want for replace if the element isn't there?
Do you want to replace the last item in the array?
Do you want to replace nothing?
Throw an error?

You can tell us here the behavior and make a pull request, or make the change for us, either is fine.

**Comment by chasebish** [comment]
Just assert that the index is in range, should be fine

**Comment by csstransky** [comment]
So throw an error for both index out of bounds, and when an Array has no elements?
That's what should be in the documentation?

**Comment by chasebish** [comment]
Yea, I’ll update it for you

**Comment by csstransky** [comment]
Cool, we'll wait for your pull request and add any more documentation for that behavior with another pull request if we find anything else.
